### ISSUE TITLE
Interpreter not showing up

### ISSUE THREAD

**Issue by x10ba** [bbonnin/zeppelin-elasticsearch-interpreter#1]
Hi,
I followed the install instructions. Updated the zeppelin-site.xml.
Restarted the daemon, but the interpreter is not showing up as available.
Any ideas?
Thanks,
x10ba

**Comment by bbonnin** [comment]
Hello
Have you checked the log ? Is there any exceptions in the log file ?

**Comment by x10ba** [comment]
Upgraded to newest version and elasticsearch now available. closeing
